# Generated by Django 5.2.13 on 2026-04-23 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platelist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platelist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blacklist/'),
        ),
        migrations.AddField(
            model_name='platelist',
            name='tag',
            field=models.CharField(blank=True, choices=[('Stolen', 'Stolen'), ('Unauthorized', 'Unauthorized'), ('Suspicious', 'Suspicious')], max_length=20, null=True),
        ),
    ]
