# Generated by Django 5.2.13 on 2026-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_platelist_added_by_platelist_image_platelist_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platelist',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
